version : '3'
services:
  db:
    image: postgres
    command : CP -R 
    restart: always
    ports: 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - chatservicenetworks

  chatservice:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chatservicenetworks
    depends_on:
      - db
    links:
      - db

networks:
  chatservicenetworks:
    name: chatservicenetworks