version : '3'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - chatservicenetworks

  chatservice:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - chatservicenetworks
    depends_on:
      - db
    links:
      - db:db

networks:
  chatservicenetworks:
    driver: bridge