# Generated by Django 4.1.5 on 2023-02-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.IntegerField(default=1675913380713),
        ),
    ]
