# Generated by Django 4.1.5 on 2023-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.IntegerField(default=1675922552441),
        ),
    ]
