# Generated by Django 4.1.5 on 2023-02-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previous',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_message', to='api.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.BigIntegerField(default=1675939432829),
        ),
    ]
