# Generated by Django 4.1.5 on 2023-02-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatrooms_delete_userchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrooms',
            old_name='user_2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatrooms',
            old_name='user_1',
            new_name='sender',
        ),
    ]
